---
parser: babel-eslint

extends: ./.eslintrc.base.yml

plugins:
  - react
  - import

settings:
  import/resolver: babel-module

rules:
  import/no-extraneous-dependencies: [2, {devDependencies: ['test/**/*.js?(x)', '**/*.spec.js?(x)']}]
