---
parser: babel-eslint

extends: shakacode

plugins:
  - react

globals:
  __DEBUG_SERVER_ERRORS__: true
  __SERVER_ERRORS__: true

env:
  browser: true
  node: true
  mocha: true

settings:
  import/resolver:
    webpack:
      config: webpack.dev.config.js

rules:
  comma-dangle: [2, never]
  key-spacing: [2, {beforeColon: false, afterColon: true, align: value}]
  max-len: [2, 120]
  no-param-reassign: 0
  no-underscore-dangle: 0
  one-var: 0

# React
  react/jsx-closing-bracket-location: [2, after-props]
  react/jsx-first-prop-new-line: [2, never]
  react/jsx-indent-props: 0
