---
parser: babel-eslint

extends: ./.eslintrc.base.yml

plugins:
  - react
  - import

settings:
  import/extensions: [.js, .jsx]
  import/resolver: babel-module

rules:
  import/no-unresolved: 0
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/extensions: 0
  import/newline-after-import: 2
  import/prefer-default-export: 2
  import/no-named-as-default: 1
  import/no-named-as-default-member: 1
  import/no-duplicates: 1
  import/no-extraneous-dependencies: [2, {devDependencies: ['test/**/*.js?(x)', '**/*.spec.js?(x)']}]
