sudo: false
language: ruby

cache:
  bundler: true
  directories:
    - client/node_modules
rvm:
  - 2.3.0
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
before_install:
  - openssl aes-256-cbc -K $encrypted_2862f5971073_key -iv $encrypted_2862f5971073_iv
    -in client_secrets.json.enc -out client_secrets.json -d
  - nvm install v5.10.0
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - npm install
script:
  - bundle exec rake test:all
addons:
  code_climate:
    repo_token: a28eb2810b0b0acd8376c2cf2b1c4aea8736e1c6854bada55fd73b740dd6261d
