default: &default
  web:
    client_id: <%= ENV.fetch("GOOGLE_CLIENT_ID") %>
    client_secret: <%= ENV.fetch("GOOGLE_CLIENT_SECRET") %>
    project_id: "effective-relic-136507"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"

development:
  <<: *default
  web:
    redirect_uris:
      - "http://localhost:3000/oauth2callback"
      - "http://localhost:4567/oauth2callback"

staging:
  <<: *default
  web:
    redirect_uris:
      - "https://u2i-confy.herokuapp.com/oauth2callback"
      - "https://u2i-confy.herokuapp.com/oauth2callback/"
      - "http://u2i-confy.herokuapp.com/oauth2callback"
      - "http://u2i-confy.herokuapp.com/oauth2callback/"
