
type: service_account
project_id: effective-relic-136507
private_key_id: <%= ENV.fetch('GOOGLE_PRIVATE_KEY_ID') %>
private_key: <%= ENV.fetch('GOOGLE_PRIVATE_KEY') %>
client_email: push-notification-register@effective-relic-136507.iam.gserviceaccount.com
client_id: <%= ENV.fetch('GOOGLE_DEFAULT_CLIENT_ID') %>
auth_uri: https://accounts.google.com/o/oauth2/auth
token_uri: https://accounts.google.com/o/oauth2/token
auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/push-notification-register%40effective-relic-136507.iam.gserviceaccount.com
